travis:
  secure:
    BINSTAR_TOKEN: hNTu8rlJyOo597Y1N1+JLaMzY/L20G+htyRNQayRdOXmsBxJOaIy018BaGKMcpIWujJT/HQKFiBAzw/THZ54Xw/949j539taPMZssppk3E/4LUv2mhjdHvg+jo6PHQePWUW8yctKCo+1WsVEv1BIcTJ7qJJITJdLaSCkbX55M9BMm0GG4InUnMRhsFgNIvX5NGP+78D3hEHisSL9QsdZPH3vnQEnN7uarw2Eo+BgXeaWMEIUiqIWqvaemWxfStcBwmc9SvIVHUjNbSOvZ0b2xSRkPs8/ajhK+Aj3gVf2ejcqWkpB6MCHfIfvaPjs7NE3QI3pF69cwamPMPxtRpG4B3kA5mqhpb8nDwxmrLnKiIPl65/Dr7SRk69QsnEg+ZpK+BFBNgz8ehGTAgmp546wZiQOZWV/ykpfMC65AhwTI/eciUxs8ZauLMaO9AiFP50MXWhn2XFcYnRzAjUc/n+BfokCt8MXvnzFnDknxVY5BeiVy7H7FC9tb6yd+KucyVRjvQezOZ912ovTn48fvedPVuU61eQipVTJr1oekhYlmsWBM1Vmxn+aSbW5qG2OpzAYjp/MLz5UEmcymAuOgCVnYANURIB0zTFT7lbiXUkmWS+8UOwTz5dn/jl/ZXrH698cwVb9yzzPCDPLtCj+IYqmejMf2qvxKviMMhtpRvRBt8U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
